Update intro slides
FIUS/theo-vorkurs-folien pull request #49
Opened 2022-10-06 11:44 UTC by ModellbahnFreak

Aktuelle Hygieneregeln und infos zum Online Vorkurs

@strutztm Könntest du die intro slides einmal durchschauen, dass das so passt.

2022-10-06 13:18 UTC, strutztm requested changes
Passt, danke

2022-10-06 13:18 UTC, strutztm commented on presentation/parts/intro-allgemein.tex
> +			\item Eine Masken\emph{fplicht} besteht aktuell nicht.
```suggestion
			\item Eine Masken\emph{pflicht} besteht aktuell nicht.
```

2022-10-06 13:18 UTC, strutztm commented on presentation/parts/intro-allgemein.tex
> +            \item Der Online-Vorkurs wird eine Übertragung aus/in einem Hösaal sein
```suggestion
            \item Der Online-Vorkurs wird eine Übertragung aus/in einem Hörsaal sein
```

2022-10-06 13:46 UTC, ModellbahnFreak commented
Ich wart' mal mit mergen bis sich der Dozent geklärt hat

2022-10-09 23:26 UTC, ModellbahnFreak commented
Scheint Hertrampf zu sein

2022-10-09 23:26 UTC, merged